[build]
  command = "make build"
  functions = "functions"
  publish = "functions"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/TechProber/pro-bot"
